// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApi.Models
{
    public partial class Genre
    {
        public Genre()
        {
            Movie = new HashSet<Movie>();
            PersonGenre = new HashSet<PersonGenre>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Movie> Movie { get; set; }
        public virtual ICollection<PersonGenre> PersonGenre { get; set; }
    }
}